pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'c225e912-8f08-4a7c-93c1-22c60f76361d', url: 'https://github.com/mantasmacionis/jenkinsproject']])
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'javac -d bin src/Student.java src/StudentTest.java --class-path ./lib/junit-platform-console-standalone-1.9.3.jar'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'java -jar lib/junit-platform-console-standalone-1.9.3.jar --class-path bin --select-class StudentTest'
                }
            }
        }
    }
}