pipeline {
    agent any

    stage('Checkout') {
        steps {
            script {
                // Git checkout
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [[$class: 'CleanBeforeCheckout']], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/mantasmacionis/jenkinsproject.git']]])
            }
        }
    }

        stage('Build') {
            steps {
                script {
                    // Compile Java files
                    sh 'javac -d . *.java'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run JUnit 5 tests
                   sh 'java -cp . StudentTest'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                     echo 'Pipeline completed successfully!'
                }
            }
        }
    }
}