pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scmGit(branches: [[name: '*/*']], extensions: [], userRemoteConfigs: [[credentialsId: 'c225e912-8f08-4a7c-93c1-22c60f76361d', url: 'https://github.com/mantasmacionis/jenkinsproject']])
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    // Compile your Java code
                    sh 'javac -d . *.java'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Run your Java tests
                    sh 'java -cp . StudentTest'
                }
            }
        }
    }
}